# Generated by Django 4.1.1 on 2022-09-29 21:27

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
