# Generated by Django 4.2.4 on 2023-09-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fortune_delete_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='category_friendship',
        ),
    ]
