# Generated by Django 4.2.4 on 2023-09-14 23:57

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_fortune_category_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='category_general',
            new_name='category_happy',
        ),
        migrations.RenameField(
            model_name='fortune',
            old_name='category_school',
            new_name='category_sad',
        ),
        migrations.AddField(
            model_name='fortune',
            name='popularity',
            field=banjo.models.FloatField(default=0.0),
        ),
    ]
