# Generated by Django 4.2.4 on 2023-09-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_category_general_fortune_category_happy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='fortune',
            name='popularity',
        ),
    ]
